### PR TITLE
ci: github actions

### PR DESCRIPTION
**Pull request by maddhruv**
Add GitHub Actions for
- Lint
- Test ESLint v4
- Test ESLint v5
- Test ESLint v6

### CODE REVIEW

**Comment by maddhruv** [comment]
@chrisbreiding are GitHub Actions disabled for the repo?

**Comment by jennifer-shehane** [comment]
Related PR: https://github.com/cypress-io/eslint-plugin-cypress/pull/50

**Comment by chrisbreiding** [comment]
Is there a need for this in addition to the Circle CI jobs? Seems like they do the same thing...

**Comment by maddhruv** [comment]
I raised this PR, as I feel GitHub Actions has better integration with GitHub and Pull Requests, and If we all agree with that, we can replace circleci with GitHub Actions, feel free to close this PR if we agree with #50

**Comment by chrisbreiding** [comment]
Thanks for clarifying. We use Circle for pretty much every cypress repo, so I think we'll keep with it for the sake of consistency.

**Pull request closed without merging**
