### PR TITLE
feat(rule): add no-focused-tests rule

### PR DESCRIPTION
**Pull request by jonathanchaffer**
Addresses #57.

### CODE REVIEW

**Comment by klausbadelt** [comment]
At the risk "plus-1ing" this (shame on me) - would love to see this merged. Just forgot an `.only` all the way thru CI... 🤭

**Comment by bossley9** [comment]
What is the status of this PR?

**Comment by DamienCassou** [comment]
What about using https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md instead? Works fine for me.

**Comment by DamienCassou** [comment]
I've forked the project and welcome PRs: https://github.com/cypress-io/eslint-plugin-cypress/issues/100.

**Comment by jonathanchaffer** [comment]
Since it looks like this project is seeing some activity again, can we bump this?
cc @nagash77 @chrisbreiding

**Comment by kasperjjit** [comment]
+1

**Comment by chiptus** [comment]
can we merge this?

**Comment by MikeMcC399** [comment]
@jonathanchaffer 

This PR has been pending for years!

I'm currently proposing some updates to this repo and I noticed this PR. I suggest instead of creating a new rule for `eslint-plugin-cypress`, use rules from [eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha).

See the existing rules from [eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha):

- [no-exclusive-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/main/docs/rules/no-exclusive-tests.md) which covers the use of `.only`

You can see an example of how `eslint-plugin-cypress` and [eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha) are combined In the [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.eslintrc) repo.

**Comment by sebb-m0** [comment]
+1

**Comment by MikeMcC399** [comment]
@jonathanchaffer 

To avoid duplicating the rules from [eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha), the README section [Mocha `.only` and `.skip`](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/README.md#mocha-only-and-skip) describes how to achieve the desired linting in a few simple steps.

The added documentation makes this PR no longer necessary, so I think it would make sense to close it now.

**Comment by MikeMcC399** [comment]
[eslint-plugin-cypress@3.0.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v3.0.0) has been released and the README on the [npm registry](https://www.npmjs.com/package/eslint-plugin-cypress) includes the instructions about how to test for .`only` and `.skip`, so as previously explained, this PR is now being closed.

**Pull request closed without merging**
