### PR TITLE
Automate docs with eslint-doc-generator

### PR DESCRIPTION
**Pull request by bmish**
I built this CLI tool [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) for automating the generation of the README rules list table and rule doc title/notices for ESLint plugins. It follows common documentation conventions from this and other top ESLint plugins and will help us standardize documentation across ESLint plugins (and generally improve the usability of custom rules through better documentation and streamline the process of adding new rules). It has 100% test coverage and is used in many of the top ESLint plugins already.

Also adds [eslint-plugin-eslint-plugin](https://github.com/eslint-community/eslint-plugin-eslint-plugin) and enables [eslint-plugin/require-meta-docs-description](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-description.md) for ensuring we have consistent descriptions defined in all rules as these are used in the generated documentation.

### CODE REVIEW

**Review by mschile — APPROVED** [review]

**Comment by cacieprins** [comment]
Hi @bmish , our CI was using an older version of node, and was failing. Can you update your forked branch from the latest, and resolve the package-lock conflicts to move this forward?

Thank you!

**Comment by bmish** [comment]
Merged master and it looks like CI is passing now!

**Comment by bmish** [comment]
@jennifer-shehane @cacieprins @mschile @chrisbreiding hey folks, all the tests/lint are now passing, I have signed the CLA, the PR is approved, so I would love to see this merged.

**Review by ddzz — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@bmish 

I've been proposing some fixes to this repo lately which have caused conflicts to your PR. There are some more PRs to come, so I suggest waiting with this PR until the repo has become more stable. There are a lot of different interdependencies and breaking changes to deal with right now.

**Comment by bmish** [comment]
Sure, I can fix the conflicts after those changes, let me know when it's ready!

**Comment by MikeMcC399** [comment]
@bmish 

I'm going to submit a separate PR to implement the doc generator as I have already made quite a lot of underlying changes in various other PRs which have been merged. I don't think it makes sense anymore to try to rebase this old PR due to the multiple conflicts that would need to be resolved. It would just be time-consuming with little benefit.

I'm going to close it now. I'll pick out the outstanding features from it and put these into additional PRs.

Thanks for your helpful initiative here!

**Comment by MikeMcC399** [comment]
@bmish 

The documents for the `eslint-plugin-cypress` have now been regenerated using your [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) so they now conform to the standards set by the generator. See PRs:

- #197 
- #198 

I would have liked to have added [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) to this repo and have it run automatically, however I found several issues that dissuaded me from implementing this step:

- https://github.com/bmish/eslint-doc-generator/issues/522
- https://github.com/bmish/eslint-doc-generator/issues/523
- https://github.com/bmish/eslint-doc-generator/issues/525

For the record, I also submitted:

- https://github.com/bmish/eslint-doc-generator/issues/526

**Pull request closed without merging**
