### PR TITLE
fix: no-assigning-return-values eslint 4, Resolves #14

### LINKED ISSUE #14: Add support for eslint 4
The new rules introduced in [2.1.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.1.0) only support eslint 5 and [cause errors in eslint 4](https://github.com/cypress-io/eslint-plugin-cypress/issues/11). Add backwards compatibility with eslint 4 so that the recommended rules can be used with it.

### PR DESCRIPTION
**Pull request by maddhruv**
Add support for ESLint v4
Resolves #14 
### Steps to Test
- `npm i eslint@4.x.x`
- `npm start`

### Ref
- https://eslint.org/docs/user-guide/migrating-to-5.0.0#parent-before-rules

### CODE REVIEW

**Comment by maddhruv** [comment]
Will add `eslint@4.x.x` CI tests after the PR is approved and merged

**Comment by chrisbreiding** [comment]
Why wait to add tests? I'd rather they be part of this PR to verify this works.

**Comment by maddhruv** [comment]
I want to separate the concerns for both the jobs (this support PR and CI jobs)

**Pull request merged**
