### PR TITLE
feat: 'unsafe-to-chain-command' added as recommended rule

### PR DESCRIPTION
**Pull request by Erik-Outreach**

### CODE REVIEW

**Review by chrisbreiding — APPROVED** [review]

**Review by BlueWinds — APPROVED** [review]

**Comment by BlueWinds** [comment]
> @BlueWinds did you have time to check on the deployment process and merging this extra PR? Please let me know if there's anything I can help with

I haven't had time to look into the deployment process. Going to see if anyone else on the team has some eyes to look into it.

**Comment by Erik-Outreach** [comment]
> > @BlueWinds did you have time to check on the deployment process and merging this extra PR? Please let me know if there's anything I can help with
> 
> I haven't had time to look into the deployment process. Going to see if anyone else on the team has some eyes to look into it.

@BlueWinds Did you find someone to have some eyes on it? It seems to me it's only some permission issue where the GH_TOKEN configured in CircleCI doesn't have the access to push changes in master: https://app.circleci.com/pipelines/github/cypress-io/eslint-plugin-cypress/127/workflows/2ccaa96c-c4ac-4613-9a40-bb75dc0eb9d9/jobs/512

**Comment by nagash77** [comment]
Hi @Erik-Outreach , thanks for the reminder.  I took a look this morning and fixed the token issue and everything should be back on track.

**Comment by Erik-Outreach** [comment]
> Hi @Erik-Outreach , thanks for the reminder. I took a look this morning and fixed the token issue and everything should be back on track.

Fix here: https://github.com/cypress-io/eslint-plugin-cypress/pull/126 - Apologises for the mistake

**Pull request merged**
