### PR TITLE
Should this be a config, not a plugin?

### PR DESCRIPTION
**Pull request by JosiMcClellan**
(I'm a student and this is my first PR anywhere, please excuse me if I do something wrong).

This doesn't seem to work currently because it's written like a [config](https://eslint.org/docs/developer-guide/shareable-configs), but calls itself a [plugin](https://eslint.org/docs/developer-guide/working-with-plugins).  A plugin takes a little extra setup, but you can do more with a it (e.g. define rules).

I just turned this into a config and it works, but if you expect to define rules in the future, please ignore this PR and structure it like a plugin instead (or I can try to).  Of course if you do accept the PR, you should also change the repo's name and description.

### CODE REVIEW

**Comment by brian-mann** [comment]
@chrisbreiding what do you think? Did we actually have this running anywhere in a project?

**Comment by brian-mann** [comment]
This is a bit too opinionated now. I think you could restrict the files to be `cypress/**` but not `_spec` or `_test` since there's nothing enforcing you from writing it that way.

Also not sure about the arrow functions - its true that when using those you cannot use mocha's `this.*` context, but it's also not required, you can write test code perfectly fine without ever using `this`.

**Comment by JosiMcClellan** [comment]
Sorry, forgot anything on the branch would be in the PR.  I'll change it back.

**Comment by brian-mann** [comment]
I think restricting the files is a good idea but just to `cypress`. Tomorrow we'll likely get this merged in.

**Comment by chrisbreiding** [comment]
Thanks for the PR. I think I'd like to keep this as a plugin, since we might add rules in the future. I realized it makes more sense to specify an `env` for Cypress instead of using `extends`, so I've done that and released [2.0.0](https://www.npmjs.com/package/eslint-plugin-cypress).

With 2.0.0, you can configure it like so:

```
{
  "plugins": [
    "cypress"
  ],
  "env": {
    "cypress/globals": true
  }
}
```

**Pull request closed without merging**
