### PR TITLE
ci: add install job

### PR DESCRIPTION
**Pull request by maddhruv**
Adds `lint`, `test`, `test:v4` and `test:v6` as separate jobs

### CODE REVIEW

**Comment by maddhruv** [comment]
@chrisbreiding Why is it not triggering `circleci` checks :thinking:

**Comment by maddhruv** [comment]
GitHub Actions PR - #51 if we are ready to go with github actions

**Comment by chrisbreiding** [comment]
Thanks a lot for this! Very useful.

**Comment by maddhruv** [comment]
@chrisbreiding can you add me as a collaborator and npm package maintainer?

**Comment by chrisbreiding** [comment]
@maddhruv Sorry, we appreciate your contributions, but we're not looking for maintainers for this package at this time.

**Comment by maddhruv** [comment]
No Problems @chrisbreiding :smile:

**Pull request merged**
